export const AUTH_SERVICE = 'AUTH_SERVICE';
export const RESERVATION_SERVICE = 'RESERVATION_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
